/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import clases.Cliente;
import clases.TablaHashEncadenamiento;
import clases.ResultadoBusqueda;
import clases.TablaHash;
import java.util.UUID;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Home extends javax.swing.JFrame {
    private static final int TAMANO_TABLA = 101; 
    private TablaHash tablaLineal;
    private TablaHashEncadenamiento tablaEncadenamientoBST;
    private javax.swing.JTextField tfCodigoCliente;
    
    
    /**
     * Creates new form JFramePrincipal
     */
    public Home() {
        initComponents();
        personalizarComponentesAdicionales();
        inicializarTablasHash();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelIngresarCliente = new javax.swing.JPanel();
        tfNombres = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfTelefono = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfDireccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfCodigoPostal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnAgregarCliente = new javax.swing.JButton();
        tfCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarDatosPrueba = new javax.swing.JButton();
        panelBuscarCliente = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfNombresB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfApellidosB = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        containLineal = new javax.swing.JScrollPane();
        textALineal = new javax.swing.JTextArea();
        containEncadenamiento = new javax.swing.JScrollPane();
        textAEncadenamiento = new javax.swing.JTextArea();
        lblTiempoBusquedaLineal = new javax.swing.JLabel();
        lblTiempoBusquedaEncadenamiento = new javax.swing.JLabel();
        lblTiempoLineal = new javax.swing.JLabel();
        lblTiempoEncadenamiento = new javax.swing.JLabel();
        lblTituloLineal = new javax.swing.JLabel();
        lblTituloEncadenamiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Comparador de Tablas Hash");

        panelIngresarCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelIngresarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelIngresarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tfNombres.setToolTipText("Nombres");

        tfApellidos.setToolTipText("Apellidos");

        jLabel2.setLabelFor(tfNombres);
        jLabel2.setText("Nombres");

        jLabel3.setLabelFor(tfApellidos);
        jLabel3.setText("Apellidos");

        tfTelefono.setToolTipText("Telefono");

        jLabel4.setLabelFor(tfTelefono);
        jLabel4.setText("Telefono");

        tfDireccion.setToolTipText("Direccion");

        jLabel5.setLabelFor(tfDireccion);
        jLabel5.setText("Direccion");

        tfCodigoPostal.setToolTipText("Codigo Postal");

        jLabel6.setLabelFor(tfCodigoPostal);
        jLabel6.setText("Código Postal");

        btnAgregarCliente.setText("Agregar cliente");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        tfCorreo.setToolTipText("Correo");

        jLabel9.setLabelFor(tfCorreo);
        jLabel9.setText("Correo");

        btnAgregarDatosPrueba.setText("Datos de prueba");
        btnAgregarDatosPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarDatosPruebaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIngresarClienteLayout = new javax.swing.GroupLayout(panelIngresarCliente);
        panelIngresarCliente.setLayout(panelIngresarClienteLayout);
        panelIngresarClienteLayout.setHorizontalGroup(
            panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarClienteLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(tfNombres)
                    .addComponent(jLabel5)
                    .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tfCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregarDatosPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        panelIngresarClienteLayout.setVerticalGroup(
            panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIngresarClienteLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelIngresarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIngresarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfCodigoPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelIngresarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCliente))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIngresarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarDatosPrueba))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelBuscarCliente.setBackground(new java.awt.Color(255, 255, 255));
        panelBuscarCliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setLabelFor(tfNombresB);
        jLabel7.setText("Nombres");

        tfNombresB.setToolTipText("Nombres");

        jLabel8.setLabelFor(tfApellidosB);
        jLabel8.setText("Apellidos");

        tfApellidosB.setToolTipText("Apellidos");

        btnBuscarCliente.setText("Buscar cliente");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarClienteLayout = new javax.swing.GroupLayout(panelBuscarCliente);
        panelBuscarCliente.setLayout(panelBuscarClienteLayout);
        panelBuscarClienteLayout.setHorizontalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(tfNombresB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(tfApellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        panelBuscarClienteLayout.setVerticalGroup(
            panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBuscarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfApellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscarCliente)))
                    .addGroup(panelBuscarClienteLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNombresB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        containLineal.setBackground(new java.awt.Color(255, 255, 255));

        textALineal.setBackground(new java.awt.Color(255, 255, 255));
        textALineal.setColumns(20);
        textALineal.setRows(5);
        textALineal.setToolTipText("Tabla Lineal");
        textALineal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textALineal.setEnabled(false);
        containLineal.setViewportView(textALineal);

        containEncadenamiento.setBackground(new java.awt.Color(255, 255, 255));

        textAEncadenamiento.setBackground(new java.awt.Color(255, 255, 255));
        textAEncadenamiento.setColumns(20);
        textAEncadenamiento.setRows(5);
        textAEncadenamiento.setToolTipText("Tabla de encadenamiento");
        textAEncadenamiento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        textAEncadenamiento.setEnabled(false);
        containEncadenamiento.setViewportView(textAEncadenamiento);

        lblTiempoBusquedaLineal.setText("Tiempo de búsqueda de la tabla lineal:");

        lblTiempoBusquedaEncadenamiento.setText("Tiempo de búsqueda de la tabla de encadenamiento:");

        lblTiempoLineal.setText("0");

        lblTiempoEncadenamiento.setText("0");

        lblTituloLineal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloLineal.setText("Tabla Lineal");

        lblTituloEncadenamiento.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTituloEncadenamiento.setText("Tabla Encadenamiento");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelIngresarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTiempoBusquedaEncadenamiento)
                                    .addComponent(lblTiempoBusquedaLineal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTiempoEncadenamiento)
                                    .addComponent(lblTiempoLineal)))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(containLineal, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(containEncadenamiento))
                            .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(lblTituloLineal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTituloEncadenamiento)
                                .addGap(198, 198, 198))))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(jLabel1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(panelIngresarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTituloLineal)
                    .addComponent(lblTituloEncadenamiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(containLineal)
                    .addComponent(containEncadenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoBusquedaLineal)
                    .addComponent(lblTiempoLineal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTiempoBusquedaEncadenamiento)
                    .addComponent(lblTiempoEncadenamiento))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void personalizarComponentesAdicionales() {
        tfCodigoCliente = new javax.swing.JTextField(UUID.randomUUID().toString().substring(0, 8));
        tfCodigoCliente.setEditable(false); // Autogenerado

        /*lblComparacionAsintotica1 = new javax.swing.JLabel("<html><b>Comparación Asintótica (Búsqueda):</b><br>" +
            "<b>Lineal:</b> Peor O(N), Promedio O(1) (con baja carga).<br>" +
            "<b>Encadenamiento BST:</b> Peor O(M) (todos al mismo bucket, BST degenerado), Promedio O(log k) (k=elementos en bucket).</html>");
        lblComparacionAsintotica1.setVerticalAlignment(javax.swing.JLabel.TOP);*/
        textALineal.setEditable(false);
        textAEncadenamiento.setEditable(false);
    }
    
    private void inicializarTablasHash() {
        tablaLineal = new TablaHash(TAMANO_TABLA);
        tablaEncadenamientoBST = new TablaHashEncadenamiento(TAMANO_TABLA);
        textALineal.setText("");
        textAEncadenamiento.setText("");
        lblTiempoLineal.setText("--- ns");
        lblTiempoEncadenamiento.setText("--- ns");
    }    
    
    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        String codigo = tfCodigoCliente.getText();
        String nombres = tfNombres.getText().trim();
        String apellidos = tfApellidos.getText().trim();
        String telefono = tfTelefono.getText().trim();
        String correo = (tfCorreo != null) ? tfCorreo.getText().trim() : nombres.toLowerCase() + "." + apellidos.toLowerCase() + "@example.com";
        String direccion = tfDireccion.getText().trim();
        String codigoPostal = tfCodigoPostal.getText().trim();

        if (nombres.isEmpty() || apellidos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Los nombres y apellidos son obligatorios.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Cliente cliente = new Cliente(codigo, nombres, apellidos, telefono, correo, direccion, codigoPostal);

        String resultadoLineal = tablaLineal.insertar(cliente);
        textALineal.append("Insertando " + nombres + " " + apellidos + ":\n  " + resultadoLineal + "\n");
        textALineal.append("-------------------------------------\n");

        String resultadoEncadenamiento = tablaEncadenamientoBST.insertar(cliente);
        textAEncadenamiento.append("Insertando " + nombres + " " + apellidos + ":\n  " + resultadoEncadenamiento + "\n");
        textAEncadenamiento.append("-------------------------------------\n");

        tfNombres.setText("");
        tfApellidos.setText("");
        tfTelefono.setText("");
        if (tfCorreo != null) tfCorreo.setText("");
        tfDireccion.setText("");
        tfCodigoPostal.setText("");
        tfCodigoCliente.setText(UUID.randomUUID().toString().substring(0, 8));
        tfNombres.requestFocus();
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        String nombresBusqueda = tfNombresB.getText().trim();
        String apellidosBusqueda = tfApellidosB.getText().trim();

        if ("".equals(nombresBusqueda) || "".equals(apellidosBusqueda)) {
            JOptionPane.showMessageDialog(this, "Los nombres y apellidos son obligatorios para la búsqueda.", "Error de Búsqueda", JOptionPane.ERROR_MESSAGE);
            return;
        }

        textALineal.append("Buscando " + nombresBusqueda + " " + apellidosBusqueda + " (Lineal):\n");
        ResultadoBusqueda resLineal = tablaLineal.buscar(nombresBusqueda, apellidosBusqueda);
        if (resLineal.getCliente() != null) {
            textALineal.append("  Encontrado: " + resLineal.getCliente().toString() + "\n");
            textALineal.append("  Intentos/Pasos: " + resLineal.getIntentos() + "\n");
        } else {
            textALineal.append("  Cliente no encontrado.\n");
            textALineal.append("  Intentos/Pasos hasta determinar no existencia: " + resLineal.getIntentos() + "\n");
        }
        lblTiempoLineal.setText(String.format("%.3f ms (%d ns)", resLineal.getTiempoNs() / 1_000_000.0, resLineal.getTiempoNs()));
        textALineal.append("-------------------------------------\n");

        textAEncadenamiento.append("Buscando " + nombresBusqueda + " " + apellidosBusqueda + " (Encadenamiento BST):\n");
        ResultadoBusqueda resEncadenamiento = tablaEncadenamientoBST.buscar(nombresBusqueda, apellidosBusqueda);
        if (resEncadenamiento.getCliente() != null) {
            textAEncadenamiento.append("  Encontrado: " + resEncadenamiento.getCliente().toString() + "\n");
            textAEncadenamiento.append("  Profundidad/Complejidad BST bucket: " + resEncadenamiento.getIntentos() + "\n");
        } else {
            textAEncadenamiento.append("  Cliente no encontrado.\n");
        }
        lblTiempoEncadenamiento.setText(String.format("%.3f ms (%d ns)", resEncadenamiento.getTiempoNs() / 1_000_000.0, resEncadenamiento.getTiempoNs()));
        textAEncadenamiento.append("-------------------------------------\n");

        tfNombresB.setText("");
        tfApellidosB.setText("");
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnAgregarDatosPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarDatosPruebaActionPerformed
        // TODO add your handling code here:
        String[] nombresPrueba = {"Ana", "Luis", "Maria", "Juan", "Sofia", "Carlos", "Laura", "Pedro", "Elena", "Diego", "Ana"}; 
        String[] apellidosPrueba = {"Garcia", "Martinez", "Lopez", "Perez", "Gomez", "Sanchez", "Diaz", "Torres", "Ruiz", "Flores", "Garcia"};

        int cantidad = 5; // O el número que desees
        for (int i = 0; i < cantidad; i++) {
            String nombre = nombresPrueba[(int)(Math.random() * nombresPrueba.length)];
            String apellido = apellidosPrueba[(int)(Math.random() * apellidosPrueba.length)];

            Cliente c = new Cliente(
                UUID.randomUUID().toString().substring(0, 8),
                nombre,
                apellido,
                "555-" + (1000 + i),
                nombre.toLowerCase() + "." + apellido.toLowerCase() + "@example.com",
                "Av. Benavides " + (100 + i),
                "0000" + i
            );
            
            String resultadoLineal = tablaLineal.insertar(c);
            textALineal.append("Insertando (prueba) " + c.getNombres() + " " + c.getApellidos() + ":\n  " + resultadoLineal + "\n");

            String resultadoEncadenamiento = tablaEncadenamientoBST.insertar(c);
            textAEncadenamiento.append("Insertando (prueba) " + c.getNombres() + " " + c.getApellidos() + ":\n  " + resultadoEncadenamiento + "\n");
        }
        textALineal.append("------------------ FIN PRUEBAS -------------------\n");
        textAEncadenamiento.append("------------------ FIN PRUEBAS -------------------\n");
    }//GEN-LAST:event_btnAgregarDatosPruebaActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarDatosPrueba;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JScrollPane containEncadenamiento;
    private javax.swing.JScrollPane containLineal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblTiempoBusquedaEncadenamiento;
    private javax.swing.JLabel lblTiempoBusquedaLineal;
    private javax.swing.JLabel lblTiempoEncadenamiento;
    private javax.swing.JLabel lblTiempoLineal;
    private javax.swing.JLabel lblTituloEncadenamiento;
    private javax.swing.JLabel lblTituloLineal;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBuscarCliente;
    private javax.swing.JPanel panelIngresarCliente;
    private javax.swing.JTextArea textAEncadenamiento;
    private javax.swing.JTextArea textALineal;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfApellidosB;
    private javax.swing.JTextField tfCodigoPostal;
    private javax.swing.JTextField tfCorreo;
    private javax.swing.JTextField tfDireccion;
    private javax.swing.JTextField tfNombres;
    private javax.swing.JTextField tfNombresB;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
